edu/urls.py
from django.urls import path
from . import views

app_name = 'edu'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('tag', views.TagStudy.as_view(), name='tag_study'),
    path('new', views.Newcontent.as_view(), name='new_content'),
]

lets/urls.py
from django.contrib import admin
from django.urls import path, include
import edu.views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('edu/', include('edu.urls')),      # edu app 의 url 을 include 한다.
    path('', edu.views.Index.as_view()),    # 첫 페이지의 url 에 app 이름이 들어가지 않도록 수정한다.
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

edu/models.py
from django.db import models

# Create your models here.
class feed(models.Model):
    content = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='image/', max_length=255, null=True, blank=True)

edu/views.py
from django.views.generic import View
from django.shortcuts import render, redirect
from.models import feed
class Index(View):
    template_name = 'index.html'

    def get(self, request):
        return render(request, self.template_name)
    
class TagStudy(View):
    template_name = 'tag_study.html'

    def get(self, request):
        f= feed.objects.all()
        return render(request, self.template_name,{'feed_list': f})
    

class Newcontent(View):
    template_name = 'upload_form.html'

    def get(self, request):
        return render(request, self.template_name)
    
    def post(self, request):
        param = request.POST.get('content', '')
        param2= request.FILES.get('up_photo', False)
        print(f"param:{param}")
        f = feed(content = param, photo=param2)
        f.save()
        return redirect('edu:tag_study')

edu/templates/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <title>렛츠코딩 입니다.</title>
        {% block extrahead %}
        {% endblock %}
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

edu/templates/index.html
{% extends 'base.html' %}
{% block content %}
    <p>환영합니다.</p>
    <p>
        <a href="https://www.naver.com">네이버</a>
        <br>
        <a href="http://letscoding.kr">
            <img src="http://letscoding.kr/img/logo.png" width='30' height='30'>
        </a>
        <br>
    </p>
{% endblock %}

edu/templates/input.html
<!DOCTYPE html>
<html>
<body>

<h2>HTML Forms</h2>

<form action="/action_page.php">
  <label for="fname">First name:</label><br>
  <input type="text" id="fname" name="fname" placeholder="성을 입력하세요."><br>
    
  <label for="lname">Last name:</label><br>
  <input type="text" id="lname" name="lname" placeholder="이름을 입력하세요."><br><br>
  
  <label for="mypwd">비밀번호:</label><br>
  <input type="password" id="mypwd" name="pwd" placeholder="비밀번호를 입력하세요."><br><br>
  
  <label for="age">나이:</label><br>
  <input id="age" type="number"name="myage" placehoder="나이를 입력해주세요."/><br>
  
  <input type="file" accept=".jpg, .png, .pdf" name= "myfiles"/><br>
  
  <input type="radio" name="country" value="kr"/>대한민국
  <input type="radio" name="country" value="cn"/>중국
  <input type="radio" name="country" value="jp"/>일본
  <input type="radio" name="country" value="nk"/>북한
  
  <br>
  
  <input type="checkbox" checked/>치킨
  <input type="checkbox"/>피자
  <input type="checkbox"/>마라탕
  <input type="checkbox"/>삼겹살
  <input type="checkbox"/>탕후루
  <input type="checkbox"/>족발
  <br>
  
  <select name="grade">
  	<option value="1">1학년</option>
    <option value="2">2학년</option>
    <option value="3">3학년</option>
    <option value="4">졸업생</option>
  </select>  
  
  <input type="range" min="100" max="500"/>
  
  <input type="date"/><br>
  
  <input type="color" name="mycolor"/><br>
  
  <input type="submit" value="제출">
</form> 

<p>If you click the "Submit" button, the form-data will be sent to a page called "/action_page.php".</p>

</body>
</html>

edu/templates/tag_study.html
{% extends "base.html" %}
{% block content %}
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Instagram_logo_2022.svg/150px-Instagram_logo_2022.svg.png"
    width = "100px"
    height = "100px"/>

<div>
<img src="/static/edu/image/profile.jpg"width="100px"/>

    <h2>Instagram</h2>
    <button>프로필 편집</button>
    <p>
        <strong>  
            손흥민<br/>
        </strong>    
        축구선수<br/>
        <a href="{% url 'edu:new_content'%}">새글등록</a>
        <ul>
            {%for feed in feed_list %}
                <li>
                    {{feed.content}}
                    <img src="/media/{{feed.photo}}" width="100px"/>
                </li>
            {% endfor %}
        </ul>
    </p>   
</div>
    <p>
        <a href="https://www.instagram.com/hm_son7/?hl=ko">
            https://www.instagram.com/hm_son7/?hl=ko </p>
        </a>

    <div>
        <div>
            <div>
                <img src="/static/edu/image/hl 1.jpg"height="35px">
            </div>
            <div>
                😊
            </div>
        </div>
        <div>
            <div>
                <img src="/static/edu/image/hl 2.jpg"height="35px">
            </div>
            <div>
                😎
            </div>
        </div>
    </div>        
    <p>
       게시물<br/>
       팔로워<br/>
       팔로우<br/>
       240<br/>
       1305만<br/>
       229<br/>
     </p>  
<div>
    <img src="/static/edu/image/thumbnails/1.jpg"width="32%"/>
    <img src="/static/edu/image/thumbnails/2.jpg"width="32%"/>
    <img src="/static/edu/image/thumbnails/3.jpg"width="32%"/>
    <img src="/static/edu/image/thumbnails/4.jpg"width="32%"/>
    <img src="/static/edu/image/thumbnails/5.jpg"width="32%"/>
    <img src="/static/edu/image/thumbnails/6.jpg"width="32%"/>
    <img src="/static/edu/image/thumbnails/7.jpg"width="32%"/>
    <img src="/static/edu/image/thumbnails/8.jpg"width="32%"/>
    <img src="/static/edu/image/thumbnails/9.jpg"width="32%"/>
</div>

{% endblock content %}

edu/templates/upload_form.html
{% extends "base.html" %}
{% block content %}
    <form action="{% url 'edu:new_content'%}" method="POST"
            enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="content"/><br>
        <input type="file" accept="image/" name="up_photo"/>
        <input type="submit" value="저장"/>
    </form>
{% endblock content %}